# Statsbomb free AFCON 2023/24 data release - Project 1

![logo.svg](attachment:logo.svg)

### Imports

In [4]:
import numpy as np
import pandas as pd

In [5]:
from statsbombpy import sb

### How 'statsbombpy' package works

When one uses the statsbombpy package in Jupyter Notebooks, one is accessing the data from the Open Data package that has been downloaded to one's local PC. 

The statsbombpy package provides a convenient way to load and work with the StatsBomb data that was downloaded locally. It does not make direct requests to the StatsBomb website to retrieve the data; instead, it reads the data from the files on one's computer.

So, when you use commands like sb.Competitions() or sb.Matches(), the statsbombpy package reads the corresponding JSON files from one's local directory and returns the data for one's analysis in Jupyter Notebook.

In [6]:
sb.matches(competition_id=1267, season_id=107)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3923881,2024-02-11,22:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Côte d'Ivoire,1,2,available,...,None,8,Final,Stade Olympique Alassane Ouattara,Dahane Beida,José Vítor dos Santos Peseiro,Emerse Faé,1.1.0,2,2
1,3923880,2024-02-10,22:00:00.000,Africa - African Cup of Nations,2023,South Africa,Congo DR,0,0,available,...,None,7,3rd Place Final,Stade Félix Houphouët-Boigny,Bamlak Tessema Weyesa,Hugo Henri Broos,Sébastien Desabre,1.1.0,2,2
2,3922838,2024-02-07,22:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Congo DR,1,0,available,...,None,6,Semi-finals,Stade Olympique Alassane Ouattara,Ibrahim Mutaz,Emerse Faé,Sébastien Desabre,1.1.0,2,2
3,3922837,2024-02-07,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,South Africa,1,1,available,...,None,6,Semi-finals,Stade de Bouaké,Amin Mohamed Omar,José Vítor dos Santos Peseiro,Hugo Henri Broos,1.1.0,2,2
4,3922242,2024-01-29,22:00:00.000,Africa - African Cup of Nations,2023,Senegal,Côte d'Ivoire,1,1,available,...,None,4,Round of 16,Stade Charles Konan Banny de Yamoussoukro,Pierre Ghislain Atcho,Aliou Cissé,Emerse Faé,1.1.0,2,2
5,3922239,2024-01-28,19:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Guinea,0,1,available,...,None,4,Round of 16,Stade Olympique Alassane Ouattara,Omar Abdulkadir Artan,Juan Micha Obiang Bicogo,Kaba Diawara,1.1.0,2,2
6,3922659,2024-02-03,19:00:00.000,Africa - African Cup of Nations,2023,Mali,Côte d'Ivoire,1,2,available,...,None,5,Quarter-finals,Stade de Bouaké,Mohamed Adel Elsaid,Éric Chelle,Emerse Faé,1.1.0,2,2
7,3922658,2024-02-03,22:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,South Africa,0,0,available,...,None,5,Quarter-finals,Stade Charles Konan Banny de Yamoussoukro,Jean Jacques Ndala Ngambo,Pedro Leitão Brito,Hugo Henri Broos,1.1.0,2,2
8,3922244,2024-01-30,19:00:00.000,Africa - African Cup of Nations,2023,Mali,Burkina Faso,2,1,available,...,None,4,Round of 16,Stade Amadou Gon Coulibaly,Ibrahim Mutaz,Éric Chelle,Hubert Velud,1.1.0,2,2
9,3922356,2024-02-02,22:00:00.000,Africa - African Cup of Nations,2023,Congo DR,Guinea,3,1,available,...,None,5,Quarter-finals,Stade Olympique Alassane Ouattara,Mustapha Ghorbal,Sébastien Desabre,Kaba Diawara,1.1.0,2,2
10,3922321,2024-02-02,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Angola,1,0,available,...,None,5,Quarter-finals,Stade Félix Houphouët-Boigny,Issa Sy,José Vítor dos Santos Peseiro,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
11,3922237,2024-01-27,19:00:00.000,Africa - African Cup of Nations,2023,Angola,Namibia,3,0,available,...,None,4,Round of 16,Stade de Bouaké,Dahane Beida,Pedro Valdemar Soares Gonçalves,Collin Benjamin,1.1.0,2,2
12,3922243,2024-01-30,22:00:00.000,Africa - African Cup of Nations,2023,Morocco,South Africa,0,2,available,...,None,4,Round of 16,Stade Laurent Pokou,Mahmood Ali Mahmood Ismail,Walid Regragui,Hugo Henri Broos,1.1.0,2,2
13,3922241,2024-01-29,19:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Mauritania,1,0,available,...,None,4,Round of 16,Stade Félix Houphouët-Boigny,Mohamed Adel Elsaid,Pedro Leitão Brito,Amir Abdou,1.1.0,2,2
14,3922240,2024-01-28,22:00:00.000,Africa - African Cup of Nations,2023,Egypt,Congo DR,1,1,available,...,None,4,Round of 16,Stade Laurent Pokou,Abongile Tom,Rui Carlos Pinho da Vitória,Sébastien Desabre,1.1.0,2,2
15,3922238,2024-01-27,22:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Cameroon,2,0,available,...,None,4,Round of 16,Stade Félix Houphouët-Boigny,Redouane Jiyed,José Vítor dos Santos Peseiro,Rigobert Song Bahanag,1.1.0,2,2
16,3920396,2024-01-18,22:00:00.000,Africa - African Cup of Nations,2023,Egypt,Ghana,2,2,available,...,None,2,Group Stage,Stade Félix Houphouët-Boigny,Pierre Ghislain Atcho,Rui Carlos Pinho da Vitória,Chris Hughton,1.1.0,2,2
17,3920386,2024-01-14,16:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Equatorial Guinea,1,1,available,...,None,1,Group Stage,Stade Olympique Alassane Ouattara,Abongile Tom,José Vítor dos Santos Peseiro,Juan Micha Obiang Bicogo,1.1.0,2,2
18,3920385,2024-01-14,19:00:00.000,Africa - African Cup of Nations,2023,Egypt,Mozambique,2,2,available,...,None,1,Group Stage,Stade Félix Houphouët-Boigny,Dahane Beida,Rui Carlos Pinho da Vitória,Francisco Queriol Conde Júnior,1.1.0,2,2
19,3920387,2024-01-14,22:00:00.000,Africa - African Cup of Nations,2023,Ghana,Cape Verde Islands,1,2,available,...,None,1,Group Stage,Stade Félix Houphouët-Boigny,Jean Jacques Ndala Ngambo,Chris Hughton,Pedro Leitão Brito,1.1.0,2,2
20,3920419,2024-01-24,22:00:00.000,Africa - African Cup of Nations,2023,Zambia,Morocco,0,1,available,...,None,3,Group Stage,Stade Laurent Pokou,Patrice Tanguy Mebiame,Avraham Grant,Walid Regragui,1.1.0,2,2
21,3920418,2024-01-24,22:00:00.000,Africa - African Cup of Nations,2023,Tanzania,Congo DR,0,0,available,...,None,3,Group Stage,Stade Amadou Gon Coulibaly,Amin Mohamed Omar,Hemed Suleiman Ali,Sébastien Desabre,1.1.0,2,2
22,3920417,2024-01-24,19:00:00.000,Africa - African Cup of Nations,2023,Namibia,Mali,0,0,available,...,None,3,Group Stage,Stade Laurent Pokou,Samuel Uwikunda,Collin Benjamin,Éric Chelle,1.1.0,2,2
23,3920416,2024-01-24,19:00:00.000,Africa - African Cup of Nations,2023,South Africa,Tunisia,0,0,available,...,None,3,Group Stage,Stade Amadou Gon Coulibaly,Issa Sy,Hugo Henri Broos,Jalel Kadri,1.1.0,2,2
24,3920415,2024-01-23,22:00:00.000,Africa - African Cup of Nations,2023,Mauritania,Algeria,1,0,available,...,None,3,Group Stage,Stade de Bouaké,Omar Abdulkadir Artan,Amir Abdou,Djamel Belmadi,1.1.0,2,2
25,3920414,2024-01-23,22:00:00.000,Africa - African Cup of Nations,2023,Angola,Burkina Faso,2,0,available,...,None,3,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Jean Jacques Ndala Ngambo,Pedro Valdemar Soares Gonçalves,Hubert Velud,1.1.0,2,2
26,3920413,2024-01-23,19:00:00.000,Africa - African Cup of Nations,2023,Gambia,Cameroon,2,3,available,...,None,3,Group Stage,Stade de Bouaké,Bamlak Tessema Weyesa,Tom Saintfiet,Rigobert Song Bahanag,1.1.0,2,2
27,3920412,2024-01-23,19:00:00.000,Africa - African Cup of Nations,2023,Guinea,Senegal,0,2,available,...,None,3,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Pacifique Ndabihawenimana,Kaba Diawara,Aliou Cissé,1.1.0,2,2
28,3920411,2024-01-22,22:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Egypt,2,2,available,...,None,3,Group Stage,Stade Félix Houphouët-Boigny,Alhadi Allaou Mahamat,Pedro Leitão Brito,Rui Carlos Pinho da Vitória,1.1.0,2,2
29,3920410,2024-01-22,22:00:00.000,Africa - African Cup of Nations,2023,Mozambique,Ghana,2,2,available,...,None,3,Group Stage,Stade Olympique Alassane Ouattara,Ibrahim Mutaz,Francisco Queriol Conde Júnior,Chris Hughton,1.1.0,2,2
30,3920409,2024-01-22,19:00:00.000,Africa - African Cup of Nations,2023,Guinea-Bissau,Nigeria,0,1,available,...,None,3,Group Stage,Stade Félix Houphouët-Boigny,Bouchra Karboubi,Baciro Candé,José Vítor dos Santos Peseiro,1.1.0,2,2
31,3920408,2024-01-22,19:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Côte d'Ivoire,4,0,available,...,None,3,Group Stage,Stade Olympique Alassane Ouattara,Mahmood Ali Mahmood Ismail,Juan Micha Obiang Bicogo,Jean-Louis Gasset,1.1.0,2,2
32,3920407,2024-01-21,22:00:00.000,Africa - African Cup of Nations,2023,South Africa,Namibia,4,0,available,...,None,2,Group Stage,Stade Amadou Gon Coulibaly,Youcef Gamouh,Hugo Henri Broos,Collin Benjamin,1.1.0,2,2
33,3920406,2024-01-21,19:00:00.000,Africa - African Cup of Nations,2023,Zambia,Tanzania,1,1,available,...,None,2,Group Stage,Stade Laurent Pokou,Djindo Louis Houngnandande,Avraham Grant,Adel Amrouche,1.1.0,2,2
34,3920405,2024-01-21,16:00:00.000,Africa - African Cup of Nations,2023,Morocco,Congo DR,1,1,available,...,None,2,Group Stage,Stade Laurent Pokou,Peter Waweru Kamaku,Walid Regragui,Sébastien Desabre,1.1.0,2,2
35,3920404,2024-01-20,22:00:00.000,Africa - African Cup of Nations,2023,Tunisia,Mali,1,1,available,...,None,2,Group Stage,Stade Amadou Gon Coulibaly,Daniel Nii Ayi Laryea,Jalel Kadri,Éric Chelle,1.1.0,2,2
36,3920403,2024-01-20,19:00:00.000,Africa - African Cup of Nations,2023,Mauritania,Angola,2,3,available,...,None,2,Group Stage,Stade de Bouaké,Mohamed Maarouf Eid Mansour,Amir Abdou,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
37,3920402,2024-01-20,16:00:00.000,Africa - African Cup of Nations,2023,Algeria,Burkina Faso,2,2,available,...,None,2,Group Stage,Stade de Bouaké,Abongile Tom,Djamel Belmadi,Hubert Velud,1.1.0,2,2
38,3920401,2024-01-19,22:00:00.000,Africa - African Cup of Nations,2023,Guinea,Gambia,1,0,available,...,None,2,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Abdel Aziz Mohamed Bouh,Kaba Diawara,Tom Saintfiet,1.1.0,2,2
39,3920400,2024-01-19,19:00:00.000,Africa - African Cup of Nations,2023,Senegal,Cameroon,3,1,available,...,None,2,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Mahmood Ali Mahmood Ismail,Aliou Cissé,Rigobert Song Bahanag,1.1.0,2,2
40,3920399,2024-01-19,16:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Mozambique,3,0,available,...,None,2,Group Stage,Stade Félix Houphouët-Boigny,Samir Guezzaz,Pedro Leitão Brito,Francisco Queriol Conde Júnior,1.1.0,2,2
41,3920398,2024-01-18,19:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Nigeria,0,1,available,...,None,2,Group Stage,Stade Olympique Alassane Ouattara,Mustapha Ghorbal,Jean-Louis Gasset,José Vítor dos Santos Peseiro,1.1.0,2,2
42,3920397,2024-01-18,16:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Guinea-Bissau,4,2,available,...,None,2,Group Stage,Stade Olympique Alassane Ouattara,Samuel Uwikunda,Juan Micha Obiang Bicogo,Baciro Candé,1.1.0,2,2
43,3920395,2024-01-17,22:00:00.000,Africa - African Cup of Nations,2023,Congo DR,Zambia,1,1,available,...,None,1,Group Stage,Stade Laurent Pokou,Bamlak Tessema Weyesa,Sébastien Desabre,Avraham Grant,1.1.0,2,2
44,3920394,2024-01-17,19:00:00.000,Africa - African Cup of Nations,2023,Morocco,Tanzania,3,0,available,...,None,1,Group Stage,Stade Laurent Pokou,Alhadi Allaou Mahamat,Walid Regragui,Adel Amrouche,1.1.0,2,2
45,3920393,2024-01-16,19:00:00.000,Africa - African Cup of Nations,2023,Tunisia,Namibia,0,1,available,...,None,1,Group Stage,Stade Amadou Gon Coulibaly,Abdulkadir Artan,Jalel Kadri,Collin Benjamin,1.1.0,2,2
46,3920392,2024-01-16,16:00:00.000,Africa - African Cup of Nations,2023,Burkina Faso,Mauritania,1,0,available,...,None,1,Group Stage,Stade de Bouaké,Jalal Jayed,Hubert Velud,Amir Abdou,1.1.0,2,2
47,3920391,2024-01-16,22:00:00.000,Africa - African Cup of Nations,2023,Mali,South Africa,2,0,available,...,None,1,Group Stage,Stade Amadou Gon Coulibaly,Mohamed Adel Hussein,Éric Chelle,Hugo Henri Broos,1.1.0,2,2
48,3920390,2024-01-15,22:00:00.000,Africa - African Cup of Nations,2023,Algeria,Angola,1,1,available,...,None,1,Group Stage,Stade de Bouaké,Issa Sy,Djamel Belmadi,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
49,3920389,2024-01-15,19:00:00.000,Africa - African Cup of Nations,2023,Cameroon,Guinea,1,1,available,...,None,1,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Ibrahim Mutaz,Rigobert Song Bahanag,Kaba Diawara,1.1.0,2,2
50,3920388,2024-01-15,16:00:00.000,Africa - African Cup of Nations,2023,Senegal,Gambia,3,0,available,...,None,1,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Redouane Jiyed,Aliou Cissé,Tom Saintfiet,1.1.0,2,2
51,3920384,2024-01-13,22:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Guinea-Bissau,2,0,available,...,None,1,Group Stage,Stade Olympique Alassane Ouattara,Amin Mohamed Omar,Jean-Louis Gasset,Baciro Candé,1.1.0,2,2

It gets a little annoying when one is constantly getting warning messages regarding the free data, so in the cell below, I decided to suppress all warning.  It is just a personal preference.

In [7]:
import warnings

# Suppress warnings
warnings.filterwarnings("ignore")

In [8]:
afcon24_matches = sb.matches(competition_id=1267, season_id=107)
afcon24_matches.head(15)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3923881,2024-02-11,22:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Côte d'Ivoire,1,2,available,...,None,8,Final,Stade Olympique Alassane Ouattara,Dahane Beida,José Vítor dos Santos Peseiro,Emerse Faé,1.1.0,2,2
1,3923880,2024-02-10,22:00:00.000,Africa - African Cup of Nations,2023,South Africa,Congo DR,0,0,available,...,None,7,3rd Place Final,Stade Félix Houphouët-Boigny,Bamlak Tessema Weyesa,Hugo Henri Broos,Sébastien Desabre,1.1.0,2,2
2,3922838,2024-02-07,22:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Congo DR,1,0,available,...,None,6,Semi-finals,Stade Olympique Alassane Ouattara,Ibrahim Mutaz,Emerse Faé,Sébastien Desabre,1.1.0,2,2
3,3922837,2024-02-07,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,South Africa,1,1,available,...,None,6,Semi-finals,Stade de Bouaké,Amin Mohamed Omar,José Vítor dos Santos Peseiro,Hugo Henri Broos,1.1.0,2,2
4,3922242,2024-01-29,22:00:00.000,Africa - African Cup of Nations,2023,Senegal,Côte d'Ivoire,1,1,available,...,None,4,Round of 16,Stade Charles Konan Banny de Yamoussoukro,Pierre Ghislain Atcho,Aliou Cissé,Emerse Faé,1.1.0,2,2
5,3922239,2024-01-28,19:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Guinea,0,1,available,...,None,4,Round of 16,Stade Olympique Alassane Ouattara,Omar Abdulkadir Artan,Juan Micha Obiang Bicogo,Kaba Diawara,1.1.0,2,2
6,3922659,2024-02-03,19:00:00.000,Africa - African Cup of Nations,2023,Mali,Côte d'Ivoire,1,2,available,...,None,5,Quarter-finals,Stade de Bouaké,Mohamed Adel Elsaid,Éric Chelle,Emerse Faé,1.1.0,2,2
7,3922658,2024-02-03,22:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,South Africa,0,0,available,...,None,5,Quarter-finals,Stade Charles Konan Banny de Yamoussoukro,Jean Jacques Ndala Ngambo,Pedro Leitão Brito,Hugo Henri Broos,1.1.0,2,2
8,3922244,2024-01-30,19:00:00.000,Africa - African Cup of Nations,2023,Mali,Burkina Faso,2,1,available,...,None,4,Round of 16,Stade Amadou Gon Coulibaly,Ibrahim Mutaz,Éric Chelle,Hubert Velud,1.1.0,2,2
9,3922356,2024-02-02,22:00:00.000,Africa - African Cup of Nations,2023,Congo DR,Guinea,3,1,available,...,None,5,Quarter-finals,Stade Olympique Alassane Ouattara,Mustapha Ghorbal,Sébastien Desabre,Kaba Diawara,1.1.0,2,2
10,3922321,2024-02-02,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Angola,1,0,available,...,None,5,Quarter-finals,Stade Félix Houphouët-Boigny,Issa Sy,José Vítor dos Santos Peseiro,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
11,3922237,2024-01-27,19:00:00.000,Africa - African Cup of Nations,2023,Angola,Namibia,3,0,available,...,None,4,Round of 16,Stade de Bouaké,Dahane Beida,Pedro Valdemar Soares Gonçalves,Collin Benjamin,1.1.0,2,2
12,3922243,2024-01-30,22:00:00.000,Africa - African Cup of Nations,2023,Morocco,South Africa,0,2,available,...,None,4,Round of 16,Stade Laurent Pokou,Mahmood Ali Mahmood Ismail,Walid Regragui,Hugo Henri Broos,1.1.0,2,2
13,3922241,2024-01-29,19:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Mauritania,1,0,available,...,None,4,Round of 16,Stade Félix Houphouët-Boigny,Mohamed Adel Elsaid,Pedro Leitão Brito,Amir Abdou,1.1.0,2,2
14,3922240,2024-01-28,22:00:00.000,Africa - African Cup of Nations,2023,Egypt,Congo DR,1,1,available,...,None,4,Round of 16,Stade Laurent Pokou,Abongile Tom,Rui Carlos Pinho da Vitória,Sébastien Desabre,1.1.0,2,2

Below, I will be using a 'for loop' to iterate over each row (match) in the afcon24_matches DataFrame using the iterrows() method. 

For each row, this method extracts 4 columns (home_team, away_team, home_score, away_score).

In short, the for loop will iterate over all matches in the DataFrame, printing the description and result for each match.

"iterrows()" is a Pandas method for iterating over each row of a DataFrame as an index-value pair. It returns an iterator that produces pairs of index and Series objects, where the index is the DataFrame index label for that row, and the Series is the actual AFCON 2023/24 data in the row.

In [23]:
# print all the matches

# I access the index of the row as "_" and the row data as "match"

# I only need the row data and not the index, So I used "_"to indicate that the index is not needed in the rest of the loop

for _, match in afcon24_matches.iterrows():
    home_team_name=match['home_team']
    away_team_name=match['away_team']
    home_score=match['home_score']
    away_score=match['away_score']
    describe_text = f'The match between {home_team_name} and {away_team_name}'
    result_text = f' finished {home_score} : {away_score}'
    print(describe_text + result_text)

The match between Nigeria and Côte d'Ivoire finished 1 : 2
The match between South Africa and Congo DR finished 0 : 0
The match between Côte d'Ivoire and Congo DR finished 1 : 0
The match between Nigeria and South Africa finished 1 : 1
The match between Senegal and Côte d'Ivoire finished 1 : 1
The match between Equatorial Guinea and Guinea finished 0 : 1
The match between Mali and Côte d'Ivoire finished 1 : 2
The match between Cape Verde Islands and South Africa finished 0 : 0
The match between Mali and Burkina Faso finished 2 : 1
The match between Congo DR and Guinea finished 3 : 1
The match between Nigeria and Angola finished 1 : 0
The match between Angola and Namibia finished 3 : 0
The match between Morocco and South Africa finished 0 : 2
The match between Cape Verde Islands and Mauritania finished 1 : 0
The match between Egypt and Congo DR finished 1 : 1
The match between Nigeria and Cameroon finished 2 : 0
The match between Egypt and Ghana finished 2 : 2
The match between Nigeria and Equatorial Guinea finished 1 : 1
The match between Egypt and Mozambique finished 2 : 2
The match between Ghana and Cape Verde Islands finished 1 : 2
The match between Zambia and Morocco finished 0 : 1
The match between Tanzania and Congo DR finished 0 : 0
The match between Namibia and Mali finished 0 : 0
The match between South Africa and Tunisia finished 0 : 0
The match between Mauritania and Algeria finished 1 : 0
The match between Angola and Burkina Faso finished 2 : 0
The match between Gambia and Cameroon finished 2 : 3
The match between Guinea and Senegal finished 0 : 2
The match between Cape Verde Islands and Egypt finished 2 : 2
The match between Mozambique and Ghana finished 2 : 2
The match between Guinea-Bissau and Nigeria finished 0 : 1
The match between Equatorial Guinea and Côte d'Ivoire finished 4 : 0
The match between South Africa and Namibia finished 4 : 0
The match between Zambia and Tanzania finished 1 : 1
The match between Morocco and Congo DR finished 1 : 1
The match between Tunisia and Mali finished 1 : 1
The match between Mauritania and Angola finished 2 : 3
The match between Algeria and Burkina Faso finished 2 : 2
The match between Guinea and Gambia finished 1 : 0
The match between Senegal and Cameroon finished 3 : 1
The match between Cape Verde Islands and Mozambique finished 3 : 0
The match between Côte d'Ivoire and Nigeria finished 0 : 1
The match between Equatorial Guinea and Guinea-Bissau finished 4 : 2
The match between Congo DR and Zambia finished 1 : 1
The match between Morocco and Tanzania finished 3 : 0
The match between Tunisia and Namibia finished 0 : 1
The match between Burkina Faso and Mauritania finished 1 : 0
The match between Mali and South Africa finished 2 : 0
The match between Algeria and Angola finished 1 : 1
The match between Cameroon and Guinea finished 1 : 1
The match between Senegal and Gambia finished 3 : 0
The match between Côte d'Ivoire and Guinea-Bissau finished 2 : 0

This line of code uses the "lineups" function from the "statsbombpy" package to retrieve the lineup data for a specific match, identified by the match_id. The match_id=3922321 part specifies that I want the lineup data for the match with the ID 3922321.

The ["Nigeria"] part is used to extract the lineup data specifically for the "Nigeria" (also known as "The Super Eagles" from the lineup data for that match.

Insert Super eagles pic

In [21]:
# "lineups" function from the "statsbombpy" package 
# Only show last 5 entries
sb.lineups(match_id=3922321)["Nigeria"].tail()

,player_id,player_name,player_nickname,jersey_number,country,cards,positions
18,31949,Zaidu Sanusi,None,3,Nigeria,[],"[{'position_id': 8, 'position': 'Left Wing Bac..."
19,34335,Terem Igobor Moffi,Terem Moffi,24,Nigeria,[],[]
20,43779,Calvin Bassey Ughelumba,Calvin Bassey,21,Nigeria,"[{'time': '54:04', 'card_type': 'Yellow Card',...","[{'position_id': 5, 'position': 'Left Center B..."
21,358410,Stanley Bobo Nwabali,None,23,Nigeria,[],"[{'position_id': 1, 'position': 'Goalkeeper', ..."
22,413688,Olorunleke Oluwasegun Ojo,Olorunleke Ojo,16,Nigeria,[],[]